# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LightState.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10LightState.proto\"R\n\nLightState\x12\x12\n\x05\x63olor\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nbrightness\x18\x02 \x01(\x01H\x01\x88\x01\x01\x42\x08\n\x06_colorB\r\n\x0b_brightness\"+\n\x0eLightStateList\x12\x19\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x0b.LightStateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LightState_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_LIGHTSTATE']._serialized_start=20
  _globals['_LIGHTSTATE']._serialized_end=102
  _globals['_LIGHTSTATELIST']._serialized_start=104
  _globals['_LIGHTSTATELIST']._serialized_end=147
# @@protoc_insertion_point(module_scope)
